dev:
  env_identifier: "dev"
  env_explanation: "DEVELOPMENT"
  db_prefix: "ds_salarys_dev"
  gcp_key: "/home/gcp_keys/gcp-key.json"
  logger_name: "logger-ds_salarys-dev"
  elastic_index: "ds_salarys_dev"
  kafka_topic: "ds_salarys_dev"
  kafka_servers:
    server1: X.X.X.X:9092
    server2: X.X.X.X:9092
    server3: X.X.X.X:9092

qa:
  env_identifier: "qa"
  env_explanation: "QA"
  db_prefix: "ds_salarys_qa"
  gcp_key: "/home/gcp_keys/gcp-key.json"
  logger_name: "logger-ds_salarys-qa"
  elastic_index: "ds_salarys_qa"
  kafka_topic: "ds_salarys_qa"
  kafka_servers:
    server1: X.X.X.X:9092
    server2: X.X.X.X:9092
    server3: X.X.X.X:9092

prod:
  env_identifier: "prod"
  env_explanation: "PRODUCTION"
  db_prefix: "ds_salarys_prod"
  gcp_key: "/home/gcp_keys/gcp-key.json"
  logger_name: "logger-ds_salarys-prod"
  elastic_index: "ds_salarys_prod"
  kafka_topic: "ds_salarys_prod"
  kafka_servers:
    server1: X.X.X.X:9092
    server2: X.X.X.X:9092
    server3: X.X.X.X:9092
